version: 2.1
on: [push]
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines
          start: npm run start-ci
          wait-on: 'http://localhost:4200'


