#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
STAGED_TEMPLATE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".hbs\{0,1\}$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"
TEMPLATE_LINT="$(git rev-parse --show-toplevel)/node_modules/.bin/ember-template-lint"

SHOULD_EXIT_JS=false
SHOULD_EXIT_TEMPL=false

if [ "$STAGED_FILES" = "" ]; then
  SHOULD_EXIT_JS=true
fi

if [ "$STAGED_TEMPLATE_FILES" = "" ]; then
  SHOULD_EXIT_TEMPL=true
fi

if $SHOULD_EXIT_JS && $STAGED_TEMPLATE_FILES; then
 exit 0
fi

PASS=true
printf "\033[32mChecking files for linter issues before committing...\033[0m\n"
# Check for eslint
if [ ! -x "$ESLINT" ]; then
  printf "\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi

if [ ! -x "$TEMPLATE_LINT" ]; then
  printf "\033[41mPlease install ember-template-lint\033[0m (npm i --save-dev ember-template-lint)"
  exit 1
fi

for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE"
  # $? is het resultaat van het laatst uitgevoerde commando
  if [ "$?" -eq 0 ]; then
  printf "\033[32mESLint Passed: $FILE\033[0m\n"
  else
  printf "\033[31mESLint Failed:\033[0m $FILE\n"
  PASS=false
  fi
done


for BESTAND in $STAGED_TEMPLATE_FILES
do
  "$TEMPLATE_LINT" "$BESTAND"
  # $? is het resultaat van het laatst uitgevoerde commando
  if [ "$?" -eq 0 ]; then
  printf "\033[32mEmber-Template-Lint Passed: $BESTAND\033[0m\n"
  else
  printf "\033[31mEmber-Template-Lint Failed:\033[0m $BESTAND\n"
  PASS=false
  fi
done



if ! $PASS; then
  printf "\033[31mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint or Ember-template-lint but do not. Please fix the Linter errors and try again!!!!\n\n"
  exit 1
else
  printf "\033[32mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
