export const newAgendaButton = '[data-test-vlc-agenda-createnewagendabutton]';
export const emberPowerSelectTrigger = '.ember-power-select-trigger';
export const emberPowerSelectOption = '.ember-power-select-option';
export const datepickerButton = '[data-test-vlc-vl-datepickerButton]';
export const flatpickrCalendar = '.flatpickr-calendar';
export const flatpickrMonthDropdownMonths = '.flatpickr-monthDropdown-months';
export const numInputWrapper = '.numInputWrapper';
export const inputNumInputCurYear = 'input.numInput.cur-year';
export const flatpickrDay = '.flatpickr-day';
export const button = 'button';
export const agendaOverviewTitleSelector = '[data-test-agendas-title]';
export const agendaListListItemDocumentsSelector ='[data-test-agenda-list-list-item-documents]'
