export const newAgendaButtonSelector = '[data-test-vlc-agenda-createnewagendabutton]';
export const emberPowerSelectTriggerSelector = '.ember-power-select-trigger';
export const emberPowerSelectOptionSelector = '.ember-power-select-option';
export const datepickerButtonSelector = '[data-test-vlc-vl-datepickerButton]';
export const flatpickrCalendarSelector = '.flatpickr-calendar';
export const flatpickrMonthDropdownMonthsSelector = '.flatpickr-monthDropdown-months';
export const numInputWrapperSelector = '.numInputWrapper';
export const inputNumInputCurYearSelector = 'input.numInput.cur-year';
export const flatpickrDaySelector = '.flatpickr-day';
export const buttonSelector = 'button';
export const agendaOverviewTitleSelector = '[data-test-agendas-title]';
export const agendaListListItemDocumentsSelector ='[data-test-agenda-list-list-item-documents]';
export const agendaAgendaItemKortBestekTabSelector ='[data-test-agenda-agendaitem-tab=agendaitem-bestek]';
